# Generated by Django 5.1.2 on 2024-12-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='name_goal',
            field=models.CharField(max_length=250),
        ),
    ]
